/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.41"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
    
    implementation("bsh:bsh:2.0b4")
    implementation("com.lowagie:itext:1.4")
    implementation("com.massisframework.j3d:java3d-core:1.6.0.1")
    implementation("org.jfree:jcommon:1.0.21")
    implementation("org.jfree:jfreechart:1.0.17")
    implementation("javax.media:jmf:2.1.1e")
    implementation("org.jogamp.jogl:jogl-all:2.3.2")
    implementation("com.massisframework.j3d:vecmath:1.6.0.1")
    // Add MASON
    implementation(fileTree("libs") { include("*.jar") })
}

application {
    // Define the main class for the application.
    mainClassName = "io.github.ragreener1.transportabm.AppKt"
}
